### ISSUE TITLE
Requirements install of copydoc asking for newer version of six

### ISSUE THREAD

**Issue by chrislkeller** [nprapps/debates#47]
Here's the terminal output when I try to install requirements... 

Worked around by:
* remove copydoc line from requirements
* install six 1.10.0
* add copydoc line back and install

```
Obtaining copydoc from git+https://github.com/nprapps/copydoc.git#egg=copydoc (from -r requirements.txt (line 15))
  Updating /Users/ckeller/.virtualenvs/debates/src/copydoc clone
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/ckeller/.virtualenvs/debates/src/copydoc/setup.py", line 39, in <module>
        'Programming Language :: Python :: 3.5',
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/ckeller/.virtualenvs/debates/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/Users/ckeller/.virtualenvs/debates/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/Users/ckeller/.virtualenvs/debates/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2306, in require
        items = working_set.resolve(reqs, env, installer)
      File "/Users/ckeller/.virtualenvs/debates/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.5.2 (/Users/ckeller/.virtualenvs/debates/lib/python2.7/site-packages), Requirement.parse('six>=1.10.0'))
```

**Comment by jjelosua** [comment]
@chrislkeller Sorry for the late response, thanks for pointing this out should be fixed soon.
